<a href="https://colab.research.google.com/github/Ola-Crrypt/Ola-Crrypt/blob/main/Home_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x=np.random.choice([6,4,3],(3,3))

print(x)


[[3 4 6]
 [3 4 6]
 [4 4 6]]


In [19]:
np.full((6,6),3)
#(row,column),num).

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

1. Create a 3 by 4 array of random integers between 3 and 10.
2. Create a 5 by 5 array  consisting 10 all through

```
# This is formatted as code
```



In [18]:
import numpy as np

x=np.random.randint(3,11,(3,4))
print(x)



[[ 7 10 10  5]
 [10  8  3 10]
 [ 8  6  5  9]]


Generate a random integer between 1 and 10.

In [42]:
np.random.randint(1,10)

2

Create a 3×3 matrix with random integers between 0 and 20.

In [52]:
np.random.randint(0,21,(3,3))

array([[18, 10, 20],
       [10, 11, 12],
       [12, 10,  0]])

Generate a 1D array of 5 random integers between 50 and 100.

In [53]:
np.random.randint(50,101,(5))

array([71, 55, 97, 57, 84])

Create a 4×2 matrix with random integers between -10 and 10.

In [55]:
np.random.randint(-10,11,(4,2))

array([[-3, 10],
       [-4, -6],
       [ 1, 10],
       [ 4, -3]])

Generate a 2×5 matrix of random numbers between 1 and 5 (inclusive of 1, exclusive of 6).

In [56]:
np.random.randint(1,5,(2,5))

array([[3, 1, 2, 2, 4],
       [4, 4, 4, 4, 1]])

Generate a 3×3 matrix with random numbers between 10 and 99 and find the maximum value

In [67]:
x=np.random.randint(10,100,(3,3))
y=np.max(x)
print(x,y)

[[45 20 72]
 [70 63 81]
 [73 34 87]] 87


Create a 5×5 matrix with random numbers between 1 and 50 and replace all even numbers with 0.

In [72]:
x=np.random.randint(1,51,(5,5))
x[x%2==0]=0
print(x)

[[ 0 11  3 37  0]
 [11  0  0 25 11]
 [19 17 21  5  0]
 [15  0 31  7  0]
 [25 43  7  0 43]]


Generate a 4×4 matrix and find the sum of all its elements

In [83]:
x=np.random.randint(0,101,(4,4))
y=np.sum(x)
print(x,y)

[[71 88 62 74]
 [98 73 68 80]
 [ 7 86 90 46]
 [30 78 45  8]] 1004


Create a 3×3 matrix with numbers between 1 and 9 and calculate the row-wise sum.

In [86]:
x=np.random.randint(1,10,(3,3))
y=np.sum(x,axis=1)
print(x,y)

[[1 6 9]
 [7 8 8]
 [3 8 1]] [16 23 12]


Generate a 2×4 matrix and find the index of the highest number

In [90]:
x=np.random.randint(0,11,(2,4))
y=np.max(x)
print(x,y)

[[10  3  7  2]
 [10  7  0  8]] 10


In [92]:

np.random.rand(10)


array([0.06258825, 0.8819086 , 0.24243235, 0.84320875, 0.94396518,
       0.01350988, 0.73160353, 0.77101434, 0.04313438, 0.92760423])

In [94]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Generate an array of 10 random numbers between 0 and 1.


In [1]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
