<a href="https://colab.research.google.com/github/Ola-Crrypt/Ola-Crrypt/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a 1D NumPy array with values from 1 to 10

'A 1D means a linear expression or a single line of number



In [ ]:
#first thing is to import NUMPY
import numpy as np
value=np.array([1,2,3,4,5,6,7,8,9,10])
print(value)

[ 1  2  3  4  5  6  7  8  9 10]


now using a loop range to solve(introducing arange)

In [ ]:
value=np.arange(1,11)
print(value)

[ 1  2  3  4  5  6  7  8  9 10]


Create a 3x3 array filled with zeros.Q2

In [29]:
z_array=np.zeros((3,3))
print(z_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create a 4x4 identity matrix.

In [38]:
iden=np.identity(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Generate an array of 10 random numbers between 0 and 1

my question cant i get whole number with deciaml without using rand it??


In [88]:
random=np.random.rand(10)
print(random)

[0.224498   0.422691   0.96246323 0.0036066  0.37675641 0.19295744
 0.07737617 0.83131825 0.39355406 0.74381823]


Create an array with even numbers from 2 to 20

In [83]:
arr_ev=np.arange(2,0,2)
print(arr_ev)


[ 2  4  6  8 10 12 14 16 18]


Find the shape and size of a given NumPy array.

<!-- why is there a comma at the end  -->

<!-- whats the difference btw size and shape?? -->

In [103]:
array=[1,2,3,4,5,6,7,8,9,10]
print(np.shape(array))
print(np.size(array))

(10,)
10


reshape an array from 1D to 2D (e.g., 1D array of size 9 to 3x3).

In [118]:
array_1D=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
#array_1D=np.array([1,2,3,4,5,6,7,8,9]
#x=array_1D.reshape(3,3)
#print(x)
print(array_1D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
